sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: TYPO3_VERSION=^7
    - php: 7.0
      env: TYPO3_VERSION=^7
    - php: 7.1
      env: TYPO3_VERSION=^8
    - php: 7.2
      env: TYPO3_VERSION=^9.5

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/minimal=$TYPO3_VERSION
  - composer show
  - export TYPO3_PATH_WEB=$PWD/.Build/Web
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs -n --standard=PSR2 Classes/
  - >
    .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/
  - >
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml Tests/Functional

