sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: TYPO3_VERSION=^7
    - php: 7.0
      env: TYPO3_VERSION=^7
    - php: 7.1
      env: TYPO3_VERSION=^8 COVERAGE="YES"
    - php: 7.2
      env: TYPO3_VERSION=^9

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/minimal=$TYPO3_VERSION
  - export TYPO3_PATH_WEB=$PWD/.Build/Web
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs -n --standard=PSR2 Classes/
  - >
    if [[ "$COVERAGE" == "YES" ]]; then  .Build/bin/phpunit --whitelist Classes/ --coverage-clover=build/logs/clover.xml --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/; else .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/; fi
  - >
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    if [[ "$COVERAGE" == "YES" ]]; then  .Build/bin/phpunit --whitelist Classes/ --coverage-clover=build/logs/clover.xml --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml Tests/Functional; else .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml Tests/Functional; fi

after_script:
  - if [[ "$COVERAGE" == "YES" ]]; then .Build/bin/php-coveralls -v; fi